-- MySQL Script generated by MySQL Workbench
-- 01/14/17 00:28:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema juz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema juz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS  DEFAULT CHARACTER SET utf8 ;
USE  ;

-- -----------------------------------------------------
-- Table user
-- -----------------------------------------------------
CREATE TABLE userTbl (
  username varchar(50) NOT NULL,
  email varchar(255) NULL,
  password varchar(32) NOT NULL,
  create_time  timestamp,
  PRIMARY KEY (username))


-- -----------------------------------------------------
-- Table group
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS groupTbl (
  groupId INT NOT NULL,
  groupName VARCHAR(45) NULL,
  PRIMARY KEY (groupId));



-- -----------------------------------------------------
-- Table groupDetails
-- -----------------------------------------------------
  CREATE TABLE IF NOT EXISTS groupDetailsTbl (
  groupRelId INT NOT NULL,
  groupId INT NULL,
  username VARCHAR(16) NULL,
  groupMemType VARCHAR(45) NULL,
  PRIMARY KEY (groupRelId),
  CONSTRAINT fk_groupDetails_1
    FOREIGN KEY (groupId)
    REFERENCES groupTbl (groupId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_groupDetails_2
    FOREIGN KEY (username)
    REFERENCES userTbl (username)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table chapterDetails
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS chapterDetailsTbl (
  chapterId INT NOT NULL,
  chapterName VARCHAR(45) NULL,
  PRIMARY KEY (chapterId));


-- -----------------------------------------------------
-- Table event
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS eventTbl (
  eventId INT NOT NULL,
  eventNm VARCHAR(45) NULL,
  eventDesc VARCHAR(45) NULL,
  eventStartDt VARCHAR(45) NULL,
  eventendDt VARCHAR(45) NULL,
  eventStatus VARCHAR(45) NULL,
  PRIMARY KEY (eventId));


-- -----------------------------------------------------
-- Table eventDetails
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS eventDetailsTbl (
  eventDetailId INT NOT NULL,
  eventId INT NULL,
  groupId INT NULL,
  PRIMARY KEY (eventDetailId),
   CONSTRAINT fk_eventDetails_1
    FOREIGN KEY (eventId)
    REFERENCES eventTbl (eventId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_eventDetails_2
    FOREIGN KEY (groupId)
    REFERENCES groupTbl (groupId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



-- -----------------------------------------------------
-- Table eventProgress
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS eventProgressTbl (
  eventProgressId INT NOT NULL,
  eventId INT NULL,
  chapterId INT NULL,
  status VARCHAR(45) NULL,
  assignedUserId VARCHAR(45) NULL,
  PRIMARY KEY (eventProgressId),
  CONSTRAINT fk_eventProgress_1
    FOREIGN KEY (chapterId)
    REFERENCES chapterDetailsTbl (chapterId)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
